### ISSUE TITLE
undefined method `filename' for File:Class

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [aeris/acme-pki#2]
When running `letsencrypt key keyname`, I get the following error:

```
/usr/lib/ruby/gems/2.3.0/gems/acme-pki-0.1.3/bin/letsencrypt:19:in `block in <top (required)>': undefined method `filename' for File:Class (NoMethodError)
Did you mean?  file?
        from /usr/lib/ruby/2.3.0/optparse.rb:1061:in `initialize'
        from /usr/lib/ruby/gems/2.3.0/gems/acme-pki-0.1.3/bin/letsencrypt:18:in `new'
        from /usr/lib/ruby/gems/2.3.0/gems/acme-pki-0.1.3/bin/letsencrypt:18:in `<top (required)>'
        from /usr/bin/letsencrypt:23:in `load'
        from /usr/bin/letsencrypt:23:in `<main>'
```

[Informations on my configurations](https://paste.frogeye.fr/?dcb7aabe45a88513#aUjI8vUFSb8A5QkQ4W345TWADMmuu4aT33PB1ANaDsg=)

I don't know much about ruby but it'ls like a dependency that is too old / recent. Maybe compare the versions with a working configuration.

**Comment by aeris** [comment]
It’s a typo on the script.
Must replace File.filename with File.basename on bin/letsencrypt, line 19
https://github.com/aeris/acme-pki/blob/master/bin/letsencrypt#L19

Will correct this on next release.
