### ISSUE TITLE
Erreur à la création d'une clé

### ISSUE THREAD

**Issue by Darathor** [aeris/acme-pki#5]
Bonjour,

J'essaie de créer une clé pour un nouveau domaine via `letsencrypt key mon-domaine.net` et j'obtiens le message d'erreur suivant :

```
Generating  private key into [path]/net.mon-domaine.pem... [KO]
/var/lib/gems/2.3.0/gems/acme-pki-0.2.1/lib/acme/pki.rb:85:in `block (2 levels) in generate_key': undefined method `to_pem' for nil:NilClass (NoMethodError)
Did you mean?  to_enum
        from /var/lib/gems/2.3.0/gems/acme-pki-0.2.1/lib/acme/pki.rb:85:in `open'
        from /var/lib/gems/2.3.0/gems/acme-pki-0.2.1/lib/acme/pki.rb:85:in `block in generate_key'
        from /var/lib/gems/2.3.0/gems/acme-pki-0.2.1/lib/acme/pki.rb:173:in `process'
        from /var/lib/gems/2.3.0/gems/acme-pki-0.2.1/lib/acme/pki.rb:78:in `generate_key'
        from /var/lib/gems/2.3.0/gems/acme-pki-0.2.1/bin/letsencrypt:48:in `<top (required)>'
        from /usr/local/bin/letsencrypt:23:in `load'
        from /usr/local/bin/letsencrypt:23:in `<main>'
```

Pour mes domaines précédents ça avait fonctionné sans difficultés mais ça date d'avant la mise à jour vers ACME v2.

Du coup j'ai testé plusieurs choses sans succès : 
- passer des paramètres -r ou -e pour forcer le type
- lancer un `gem update`
- revenir aux versions des gemmes listées dans les dépendances (des fois que ce soit une mise à jour mineure qui casse un truc)
- désinstaller et réinstaller acme-pki

Alors je me suis dit que ça pouvait être un bug introduit dans la dernière version et j'ai regardé les différences de code entre la version 0.1.5 et 0.2.1 d'acme-pki mais sans rien trouver qui pourrait expliquer ça (après je ne connais pas vraiment ruby donc j'ai pu rater des trucs).

Du coup je sèche un peu...

Merci d'avance pour tout élément qui m'aiderait à résoudre mon problème.

**Comment by aeris** [comment]
Merci du retour !
Corrigé dans la v0.2.2 du coup :blush:

**Comment by Darathor** [comment]
Nickel, ça fonctionne ! Merci pour la rapidité du correctif ^^
